In [2]:
import re

In [11]:
#for example
text = 'this is a good day'

In [12]:
#now lets see the good they or not
if re.search('good',text):
    print('Wonderful!')
else:
    print("Alas:(")

Wonderful!


In [18]:
text = "Amy works diligently. Amy gets good grades- Our student Amy is succesful."

In [19]:
re.split("Amy",text)

['',
 ' works diligently. ',
 ' gets good grades- Our student ',
 ' is succesful.']

In [23]:
re.findall("Amy",text)

['Amy', 'Amy', 'Amy']

In [24]:
# .search() for some pattern and return a boolean
# .split() will use a pattern for creating a list of substrings.
# .findall() will look for a pattern and pull out all occurences

In [29]:
text = "Amy works diligently. Amy gets good grades- Our student Amy is succesful."


re.search("Amy",text)

<re.Match object; span=(0, 3), match='Amy'>

# Patterns and characters Classes

In [71]:
grades = "BAADBCAAAAABCACABCCCABACAAAB"

In [72]:
re.findall("AB",grades)

['AB', 'AB', 'AB', 'AB']

In [99]:
re.findall('[\AB]\[C]',grades)

error: bad escape \A at position 1

In [74]:
re.findall("AB|AC",grades)

['AB', 'AC', 'AB', 'AB', 'AC', 'AB']

In [75]:
re.findall("[^D]",grades)



['B',
 'A',
 'A',
 'B',
 'C',
 'A',
 'A',
 'A',
 'A',
 'A',
 'B',
 'C',
 'A',
 'C',
 'A',
 'B',
 'C',
 'C',
 'C',
 'A',
 'B',
 'A',
 'C',
 'A',
 'A',
 'A',
 'B']

In [76]:
re.findall("A{2,10}",grades)

['AA', 'AAAAA', 'AAA']

In [79]:
re.findall("A{1,1}A{1,2}",grades)

['AA', 'AAA', 'AA', 'AAA']

In [81]:
re.findall("A{1,10}B{1,10}C{1,10}",grades)

['AAAAABC', 'ABCCC']

In [84]:
with open("datasets/ferpa.txt","r") as file:
    
    wiki = file.read()
wiki

'Overview[edit]\nFERPA gives parents access to their child\'s education records, an opportunity to seek to have the records amended, and some control over the disclosure of information from the records. With several exceptions, schools must have a student\'s consent prior to the disclosure of education records after that student is 18 years old. The law applies only to educational agencies and institutions that receive funds under a program administered by the U.S. Department of Education.\n\nOther regulations under this act, effective starting January 3, 2012, allow for greater disclosures of personal and directory student identifying information and regulate student IDs and e-mail addresses.[2] For example, schools may provide external companies with a student\'s personally identifiable information without the student\'s consent.[2]\n\nExamples of situations affected by FERPA include school employees divulging information to anyone other than the student about the student\'s grades o

In [85]:
re.findall("[a-zA-Z]{1,100}\[edit\]",wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [103]:
re.findall("[\w]{1,100}\[edit\]",wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [107]:
re.findall(".*\[edit\]",wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [113]:
for item in re.finditer("([\w ]*)(\[edit\])",wiki):
                        print(item.groups(1))

('Overview', '[edit]')
('Access to public records', '[edit]')
('Student medical records', '[edit]')


In [114]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [126]:
import numpy as np
a = np.random.randint(400,size=(20,20))
b = np.random.randint(400,size=(20,20))
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 


l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20, 1)))

<ipython-input-126-bf9a6744cfbb>:6: RuntimeWarning: invalid value encountered in power
  result = result ** 0.5


nan

In [6]:
import numpy as np
a2 = np.random.rand(4, 2)
a2

array([[0.71237524, 0.72570025],
       [0.65797187, 0.22134671],
       [0.36710278, 0.16613717],
       [0.18013127, 0.43714497]])

In [8]:
a1 = np.random.rand(4)
a1

array([0.64274044, 0.75556922, 0.82995618, 0.39499017])

In [22]:
a4 = np.arange(1, 4, 1)
a4.ndim == 1

True

In [14]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a1 == a2


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [32]:
import re 
s = 'ACBCAC'


re.findall('^[AC]', s)

['A']

In [33]:
a4 = np.arange(1, 4, 1)

In [34]:
a4

array([1, 2, 3])

In [35]:
a4 = np.arange(1, 4, 1)

In [36]:
a4

array([1, 2, 3])

In [37]:
a4.shape

(3,)

In [38]:
a2 = np.random.rand(4, 1)

In [39]:
a2

array([[0.0086706 ],
       [0.73910572],
       [0.42508996],
       [0.72004119]])

In [40]:
a2.shape

(4, 1)

In [46]:
a1 = np.random.rand(4)
a1

array([0.3462818 , 0.76433284, 0.11436006, 0.9776553 ])

In [42]:
a1.shape

(4,)

In [43]:
a5 = np.linspace(1 ,4, 4)

In [44]:
a5

array([1., 2., 3., 4.])

In [45]:
a5.shape

(4,)

In [49]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(L)

5


In [15]:
import re
simple_string = """Amy is 5 years old, and her sister Mary is 2 years old. 
Ruth and Peter, their parents, have 3 kids."""
a = re.findall("[A-Z][a-z]*", simple_string)
len(a)

4

In [25]:
simple_string = """
Ronald Mayr: A
Bell Kassulke: B
Jacqueline Rupp: A 
Alexander Zeller: C
Valentina Denk: C 
Simon Loidl: B 
Elias Jovanovic: B 
Stefanie Weninger: A 
Fabian Peer: C 

"""

a = re.findall("[A-Z][a-z]* [A-Z][a-z]*\:[ ][B]",simple_string)
string_a = "".join(str(item) for item in a)
names = re.findall("[A-Z][a-z]* [A-Z][a-z]*",string_a)
names


['Bell Kassulke', 'Simon Loidl', 'Elias Jovanovic']